
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: siva9666/frontend:1.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend
          items:
          - key: nginx.conf
            path: nginx.conf

