apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-backend
  namespace: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-backend
  template:
    metadata:
      labels:
        app: expense-backend
    spec:
      containers:
      - name: expense-backend
        image: siva9666/backend:1.0 # Replace with your actual backend image
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: expense-config
              key: DB_HOST
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: expense-config
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: expense-secrets
              key: DB_USER
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: expense-secrets
              key: DB_PWD
