apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: expense
data:
  init-script.sql: |
    CREATE DATABASE IF NOT EXISTS transactions;
    CREATE USER 'expense'@'%' IDENTIFIED BY 'ExpenseApp@1';
    GRANT ALL PRIVILEGES ON transactions.* TO 'expense'@'%';
    FLUSH PRIVILEGES;
